function [] = write2xls(par, flag)
if flag == 1
	%% 输出表头
	title = {'ID', '缺陷类型', '全阵列盲元数', '全阵列最大盲元簇', ...
		'A区盲元数', 'A区最大盲元簇', '全阵列坏行坏列', 'A区坏行坏列', ...
		'A区斑块', '最大斑块尺度', '最大斑块深度', 'A区底纹', ...
		'1/4最大底纹长度', '1/4最大底纹面积', '1/4最小底纹占比', ...
		'1/8最大底纹长度', '1/8最大底纹面积', '1/8最小底纹占比'};
% 	title = [title, par.windowInfo];
	xlswrite(par.resultFileName, title, 1, 'A1');
else
	%% 输出单个芯片测试结果
	singleRes = {par.ID, par.label, par.BP_Num, par.maxCrowd, ...
		par.A_BP_Num, par.A_maxCrowd, par.CR_Num, par.A_CR_Num, ...
		par.A_spot,  par.maxSpotScale, par.maxSpotDepth, par.A_shadow, ...
		par.maxLen4, par.maxArea4, par.minRatio4, ...
		par.maxLen8, par.maxArea8, par.minRatio8};
	xlswrite(par.resultFileName, singleRes, 1, ['A', num2str(flag)]);
end
end